---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgBkVbGN78Vav15Y5vdLtV7v7LYlLI94c9JPjsd0pGgclG6qDKgNCLg9mRJV6e/dUuACkdo2yUUx/78x6alKeFCekcXua5Ev67y3gdiWRob7OH5IGCKmnLMg6GBqBNRtdTyJB/zYkKdfT6P9s5buiqYzhiDyVsTLc8h8S/SRGv3FYkI1GVIp3TCaVobNNiYW7Qo5vvnbPk+swhKFPRpkri2VnaIJA8+4FMyCGYHWzfaQr7w6g6BlaoLmwzcm7tNXUuOgpruImfFgXDUNMqe+dB3uzqt2BZgi6IUK4re//URpxh4Zoi/nLIS3o9axEz7WmPtejOOtb+XWyINBJKFBR9NmGGwpFg4sIvXRrpktZ0tPvp4sf2FzbL9NFYDl7rrqyWJKPcqBfCw8Z7tyJUmp8bjyRkvxN03ne3XHmYXS6i0EqR8MSvItJC9nFFffb9XQSOX+tZWHI6AgYrhknLb13I43t7YrXglw2kJqgdibuxbDOT5VbhFS9/2GpUMvlneP/1pNo9mw+8HVMqEdLXhGvi2DLjGzW8ySxbs8Zjwrj8NTpvyK21QSVjo3LMB5sioZAov7xh6aHpcM7q2W/METSF8bogHK8zraKLbGABjLm3XVRkfFSaqpDU4UnvEnuzuJoa1rHrgs5cW1wN3GuGuM3fawTAh9SP0kBwriil0H2t+DFczzY7Hqwiu4H1gSellXF8cAYEWjcyWc
    username: AgA1d2Kxj1O8HV1TbSEDM2fva1I6fkXoheCTkcyN+BkOjQts3t54HVK6E705bLbho1ws4Q2C2eTHM25EoZMFjcF70VRptf1K2FejGFGLaB+u2dD4mgybVKhHqludJwYjbE1oKD9RRnxU0O0Cd/l7ZJ12anzzDCiMTVE163x/6iRZZ9cHoKOx3cc/cYqpcHpTvQU4iTJtcWqWZng10uo1NuxvrkrK2HN6ocybUZpQYZTRF4AD3WBHrvk1X3d/tMY2Xntm7vuMZz2MfNJLipWRP/hFui3mYvLOwrdzAxjXZ5asGvXAKvkxaBDKgWh+ufwvnSHogBydlSc82MTUDbzuShukzB34s2a2rRWlUy9UA/OKzkvZwKr2Vo4kZqtX+1Hvlvg+6AQRMLOWG1JUQwzyO7oSR0m9UCiGyqx82MGPL5CxbezwNYpL+NtdGQRFfBVqQXZNDCuzP5JT1GqWQXZYD4S9gKazT1LDs9xeZQJXiNbrokTTkUYRa/00zPSpKEisfsTgyptmxp8ovyFvQBNxP+01ofZD9yJ7USo8ATYE5KRDLdpWsOrrOKrmA2y12Up38R1yeZEOH2m5b6XuVIsE+XOF9LV8xCtET8jlZ77xHz6NpuD1R241e3av3mbH2wHuRU/j/VczqscSuzSO6XxS7Vn9XJ5rv3ZW9ayJWhKCAAUeY5IvONbBU+EeMzqWv7XdsG14FCcyFg==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
