apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgB0c34xX2... # Your encrypted password
    username: AgD1Ukw... # Your encrypted username
  template:
    metadata:
      name: db-creds
      namespace: default
